version: '3'

services:
  pg:
    image: postgres:17-alpine3.21
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

    
