[app]
mode='production'

[http_api]
host = "0.0.0.0"
port = 8000
base_url_prefix = "/api/v1"

[grpc_api]
port = 55031

[db]
host = "auth.postgres"
port = 54321
database = "authDb"
user = "postgres"
password = "1234"
migration = true
logging = true
max_idle_connection = 100